# Generated by Django 5.2.14 on 2026-06-04 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_eventregistration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='status',
            field=models.CharField(choices=[('Pending Super Admin Approval', 'Pending Super Admin Approval'), ('Pending Parent Community Approval', 'Pending Parent Community Approval'), ('Approved', 'Approved'), ('Rejected By Super Admin', 'Rejected By Super Admin'), ('Rejected By Parent Community Admin', 'Rejected By Parent Community Admin'), ('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Pending', 'Pending')], default='Pending Super Admin Approval', max_length=100),
        ),
        migrations.AlterField(
            model_name='community',
            name='type',
            field=models.CharField(choices=[('Subsidiary', 'Subsidiary'), ('Super', 'Super'), ('Subsidiary Community', 'Subsidiary Community'), ('Super Community', 'Super Community')], default='Super', max_length=50),
        ),
        migrations.CreateModel(
            name='CommunityApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_level', models.CharField(max_length=100)),
                ('approved_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, default='')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_history', to='api.community')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('notification_type', models.CharField(default='info', max_length=50)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
