# Generated by Django 5.2.14 on 2026-06-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_community_status_alter_community_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='caste',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='est_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='office_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='registration_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='sub_caste',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='website',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
