# Generated by Django 5.2.14 on 2026-06-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_community_caste_community_email_community_est_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='doc_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='social_fb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='social_tw',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='social_yt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='vision_mission',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('Verified', 'Verified'), ('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Suspended', 'Suspended'), ('Active', 'Active'), ('Inactive', 'Inactive')], default='Pending', max_length=50),
        ),
    ]
