# Generated by Django 5.2.14 on 2026-06-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_community_doc_name_community_social_fb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='aadhaar_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
