# Generated by Django 5.2.14 on 2026-06-05 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_member_business_category_member_business_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_groups', to='api.member'),
        ),
        migrations.AlterField(
            model_name='family',
            name='village',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='occupation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='relation',
            field=models.CharField(default='Other', max_length=100),
        ),
    ]
