# Generated by Django 5.2.14 on 2026-06-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_familymember_business_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
