# Generated by Django 5.2.14 on 2026-06-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_role_subscriptionplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('Hero Banner', 'Hero Banner'), ('Sidebar Top', 'Sidebar Top'), ('Sidebar Bottom', 'Sidebar Bottom'), ('Footer', 'Footer'), ('Content Inline', 'Content Inline')], max_length=50)),
                ('advertiser', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/')),
                ('destination_url', models.URLField(blank=True, max_length=500, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Paused', 'Paused'), ('Expired', 'Expired')], default='Active', max_length=50)),
                ('priority', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
