# Generated by Django 5.2.14 on 2026-06-08 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_community_district_alter_community_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='custom_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='api.role'),
        ),
        migrations.AddField(
            model_name='member',
            name='permissions',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
