# Generated by Django 5.2.14 on 2026-06-08 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_member_custom_role_member_permissions_role_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee_members', to='api.role'),
        ),
    ]
