# Generated by Django 5.2.14 on 2026-06-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_committee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
