# Generated by Django 5.2.14 on 2026-06-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_community_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='visibility_scope',
            field=models.CharField(default='COMMUNITY_ONLY', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='visibility_scope',
            field=models.CharField(default='COMMUNITY_ONLY', max_length=50),
        ),
        migrations.AddField(
            model_name='gallery',
            name='visibility_scope',
            field=models.CharField(default='COMMUNITY_ONLY', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='visibility_scope',
            field=models.CharField(default='COMMUNITY_ONLY', max_length=50),
        ),
        migrations.AddField(
            model_name='news',
            name='visibility_scope',
            field=models.CharField(default='COMMUNITY_ONLY', max_length=50),
        ),
    ]
