# Generated by Django 5.2.14 on 2026-06-10 06:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_business_visibility_scope_event_visibility_scope_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matrimonyprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='matrimonyprofile',
            name='visibility_settings',
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='aadhaar',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='allow_direct_chat',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='allow_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='allow_interests',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='allow_phone',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='allow_whatsapp',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='children_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='children_living_with',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='complexion',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='contact_permission',
            field=models.CharField(default='Everyone Who Can View', max_length=100),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='current_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='diet',
            field=models.CharField(default='Vegetarian', max_length=50),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='divorce_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='drinking',
            field=models.CharField(default='No', max_length=50),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='driving_license',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='family_member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matrimony_profile', to='api.familymember'),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='filter_castes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='filter_cities',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='filter_communities',
            field=models.ManyToManyField(blank=True, related_name='filtered_matrimony_profiles', to='api.community'),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='filter_gender',
            field=models.CharField(default='Everyone', max_length=50),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='filter_max_age',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='filter_min_age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='filter_states',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='filter_sub_castes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='has_children',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='languages_known',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='mother_tongue',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='native_place',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='pan',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='passport',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='religion',
            field=models.CharField(default='Hindu', max_length=100),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='selected_communities',
            field=models.ManyToManyField(blank=True, related_name='visible_matrimony_profiles', to='api.community'),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='smoking',
            field=models.CharField(default='No', max_length=50),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='visibility_scope',
            field=models.CharField(default='My Community Only', max_length=100),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='widowed_children_info',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='year_of_loss',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnerpreference',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_preference', to='api.matrimonyprofile'),
        ),
        migrations.AlterField(
            model_name='interestrequest',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_interests', to='api.matrimonyprofile'),
        ),
        migrations.AlterField(
            model_name='interestrequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_interests', to='api.matrimonyprofile'),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='about',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='age',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='education',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='height',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='income',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='marital_status',
            field=models.CharField(default='Never Married', max_length=50),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='profession',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_matrimony_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='partnerpreference',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MatrimonyAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='api.matrimonyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MatrimonyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='matrimony_photos/')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(choices=[('Profile Photo', 'Profile Photo'), ('Family Photo', 'Family Photo'), ('Lifestyle Photo', 'Lifestyle Photo')], default='Profile Photo', max_length=50)),
                ('is_private', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.matrimonyprofile')),
            ],
        ),
    ]
