# Generated by Django 5.2.14 on 2026-06-11 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_matrimonyprofile_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrimonyprofile',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='contact_relation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='contact_whatsapp',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Ready For Review', 'Ready For Review'), ('Active', 'Active'), ('Hidden', 'Hidden'), ('Suspended', 'Suspended'), ('Deleted', 'Deleted')], default='Draft', max_length=50),
        ),
    ]
