# Generated by Django 5.2.14 on 2026-06-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_add_contact_fields_to_matrimony_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrimonyprofile',
            name='review_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Ready For Review', 'Ready For Review'), ('Active', 'Active'), ('Featured', 'Featured'), ('Rejected', 'Rejected'), ('Hidden', 'Hidden'), ('Suspended', 'Suspended'), ('Deleted', 'Deleted')], default='Draft', max_length=50),
        ),
    ]
