# Generated by Django 5.2.14 on 2026-06-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_add_review_notes_to_matrimony_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrimonyprofile',
            name='filter_educations',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='filter_marital_statuses',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='filter_occupations',
            field=models.TextField(blank=True, default=''),
        ),
    ]
