# Generated by Django 5.2.14 on 2026-06-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_matrimonyprofile_filter_educations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrimonyprofile',
            name='visibility_hierarchy',
            field=models.CharField(default='My Community', max_length=100),
        ),
    ]
