# Generated by Django 5.2.15 on 2026-06-11 08:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_matrimonyprofile_visibility_hierarchy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='matrimonyprofile',
            old_name='filter_castes',
            new_name='target_castes',
        ),
        migrations.RenameField(
            model_name='matrimonyprofile',
            old_name='filter_cities',
            new_name='target_cities',
        ),
        migrations.RenameField(
            model_name='matrimonyprofile',
            old_name='filter_educations',
            new_name='target_educations',
        ),
        migrations.RenameField(
            model_name='matrimonyprofile',
            old_name='filter_marital_statuses',
            new_name='target_marital_statuses',
        ),
        migrations.RenameField(
            model_name='matrimonyprofile',
            old_name='filter_occupations',
            new_name='target_occupations',
        ),
        migrations.RenameField(
            model_name='matrimonyprofile',
            old_name='filter_states',
            new_name='target_states',
        ),
        migrations.RenameField(
            model_name='matrimonyprofile',
            old_name='filter_sub_castes',
            new_name='target_subcastes',
        ),
        migrations.RemoveField(
            model_name='matrimonyprofile',
            name='filter_communities',
        ),
        migrations.RemoveField(
            model_name='matrimonyprofile',
            name='filter_gender',
        ),
        migrations.RemoveField(
            model_name='matrimonyprofile',
            name='filter_max_age',
        ),
        migrations.RemoveField(
            model_name='matrimonyprofile',
            name='filter_min_age',
        ),
        migrations.RemoveField(
            model_name='matrimonyprofile',
            name='visibility_hierarchy',
        ),
        migrations.RemoveField(
            model_name='matrimonyprofile',
            name='visibility_scope',
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='audience_count_cache',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='hierarchy_scope',
            field=models.CharField(db_index=True, default='My Community', max_length=100),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='target_age_max',
            field=models.IntegerField(db_index=True, default=60),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='target_age_min',
            field=models.IntegerField(db_index=True, default=18),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='target_communities',
            field=models.ManyToManyField(blank=True, related_name='targeted_matrimony_profiles', to='api.community'),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='target_gender',
            field=models.CharField(db_index=True, default='Everyone', max_length=50),
        ),
        migrations.AddField(
            model_name='matrimonyprofile',
            name='visibility_type',
            field=models.CharField(choices=[('PRIVATE', 'Private'), ('COMMUNITY_NETWORK', 'Community Network'), ('CUSTOM_AUDIENCE', 'Custom Audience'), ('PLATFORM_WIDE', 'Platform Wide')], db_index=True, default='COMMUNITY_NETWORK', max_length=50),
        ),
        migrations.AddIndex(
            model_name='matrimonyprofile',
            index=models.Index(fields=['visibility_type'], name='api_matrimo_visibil_c13b4d_idx'),
        ),
        migrations.AddIndex(
            model_name='matrimonyprofile',
            index=models.Index(fields=['gender'], name='api_matrimo_gender_cf3d6e_idx'),
        ),
        migrations.AddIndex(
            model_name='matrimonyprofile',
            index=models.Index(fields=['age'], name='api_matrimo_age_250fe8_idx'),
        ),
        migrations.AddIndex(
            model_name='matrimonyprofile',
            index=models.Index(fields=['state'], name='api_matrimo_state_83f069_idx'),
        ),
    ]
