# Generated by Django 5.2.15 on 2026-06-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_rename_filter_castes_matrimonyprofile_target_castes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
        migrations.AddField(
            model_name='campaign',
            name='updates',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='donation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='receipt_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='matrimonyprofile',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Ready For Review', 'Ready For Review'), ('Pending Approval', 'Pending Approval'), ('Active', 'Active'), ('Approved', 'Approved'), ('Featured', 'Featured'), ('Rejected', 'Rejected'), ('Hidden', 'Hidden'), ('Suspended', 'Suspended'), ('Deleted', 'Deleted')], default='Draft', max_length=50),
        ),
    ]
