# Generated by Django 5.2.15 on 2026-06-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_campaign_end_date_campaign_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(default='Cultural', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='gallery',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='schedule',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='event',
            name='speakers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='family_members_attending',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='special_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='status',
            field=models.CharField(default='Registered', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending Approval', 'Pending Approval'), ('Published', 'Published'), ('Registration Open', 'Registration Open'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Published', max_length=50),
        ),
    ]
