# Generated by Django 5.2.14 on 2026-06-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_event_category_event_end_time_event_gallery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='call_clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='business',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='businesses/covers/'),
        ),
        migrations.AddField(
            model_name='business',
            name='cover_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='gallery',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='hours',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='opens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='business',
            name='socials',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='business',
            name='website',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='website_visits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='business',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='whatsapp_clicks',
            field=models.IntegerField(default=0),
        ),
    ]
