# Generated by Django 5.2.14 on 2026-06-12 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_business_address_business_call_clicks_business_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('mobile', models.CharField(max_length=20)),
                ('alt_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('occupation', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('experience', models.CharField(max_length=100)),
                ('relevant_experience', models.CharField(blank=True, max_length=100, null=True)),
                ('current_salary', models.CharField(blank=True, max_length=100, null=True)),
                ('expected_salary', models.CharField(blank=True, max_length=100, null=True)),
                ('notice_period', models.CharField(blank=True, max_length=100, null=True)),
                ('qualification', models.CharField(max_length=255)),
                ('skills', models.TextField()),
                ('resume', models.FileField(upload_to='resumes/')),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('portfolio', models.URLField(blank=True, max_length=500, null=True)),
                ('linkedin', models.URLField(blank=True, max_length=500, null=True)),
                ('github', models.URLField(blank=True, max_length=500, null=True)),
                ('why_interested', models.TextField(blank=True, null=True)),
                ('willing_to_relocate', models.BooleanField(default=False)),
                ('available_joining_date', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Under Review', 'Under Review'), ('Shortlisted', 'Shortlisted'), ('Interview Scheduled', 'Interview Scheduled'), ('Selected', 'Selected'), ('Rejected', 'Rejected')], default='Applied', max_length=50)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='api.community')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='api.job')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='api.member')),
            ],
        ),
    ]
