# Generated by Django 5.2.14 on 2026-06-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_message_reply_to_messagereaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email_verified',
            field=models.BooleanField(default=True),
        ),
    ]
