# Generated by Django 5.2.14 on 2026-06-16 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_member_email_verified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=255)),
                ('property_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('ownership_type', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Draft', 'Draft'), ('Archived', 'Archived')], default='Draft', max_length=50)),
                ('contact_person', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=50)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField()),
                ('area', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('pincode', models.CharField(blank=True, default='', max_length=20)),
                ('google_map_url', models.URLField(blank=True, default='', max_length=500)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('rules', models.TextField(blank=True, default='')),
                ('terms_conditions', models.TextField(blank=True, default='')),
                ('cancellation_policy', models.TextField(blank=True, default='')),
                ('refund_policy', models.TextField(blank=True, default='')),
                ('amenities', models.JSONField(blank=True, default=list, null=True)),
                ('resources', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='api.community')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('brochure', 'Brochure')], max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='property_media/')),
                ('file_url', models.URLField(blank=True, default='', max_length=500)),
                ('sort_order', models.IntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='api.property')),
            ],
        ),
    ]
