# Generated by Django 5.2.15 on 2026-06-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_remove_propertymedia_property_bookingproperty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingproperty',
            name='alternate_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bookingproperty',
            name='approval_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bookingproperty',
            name='cancellation_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bookingproperty',
            name='cancellation_hours',
            field=models.IntegerField(default=24),
        ),
        migrations.AddField(
            model_name='bookingproperty',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='bookingproperty',
            name='internal_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bookingproperty',
            name='manual_payment_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bookingproperty',
            name='refund_percentage',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='bookingproperty',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bookingproperty',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bookingproperty',
            name='terms_conditions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='propertyresource',
            name='full_day_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='propertyresource',
            name='half_day_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='propertyresource',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='propertyresource',
            name='max_booking_duration_hours',
            field=models.IntegerField(default=24),
        ),
        migrations.AddField(
            model_name='propertyresource',
            name='min_booking_duration_hours',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='propertyresource',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bookingproperty',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending Approval', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Inactive', 'Inactive')], default='Pending Approval', max_length=50),
        ),
        migrations.AlterField(
            model_name='venuebooking',
            name='purpose',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='venuebooking',
            name='status',
            field=models.CharField(choices=[('Pending Approval', 'Pending Approval'), ('Approved', 'Approved'), ('Payment Submitted', 'Payment Submitted'), ('Confirmed', 'Confirmed'), ('Checked In', 'Checked In'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Hold', 'Hold'), ('Rejected', 'Rejected')], default='Pending Approval', max_length=50),
        ),
    ]
