# Generated by Django 5.2.15 on 2026-06-17 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_booking_workflow_finance_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenuePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='venues/%Y/%m/%d/')),
                ('photo_type', models.CharField(choices=[('Cover', 'Cover Image'), ('Gallery', 'Gallery Image')], default='Gallery', max_length=20)),
                ('order', models.IntegerField(default=0, help_text='Order of photos (0 = first/cover)')),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_set', to='api.bookingproperty')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
