# Generated by Django 5.2.15 on 2026-06-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_venuephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingproperty',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='VenuePhoto',
        ),
    ]
