# Generated by Django 5.2.15 on 2026-06-18 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_bookingproperty_notified_delete_venuephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyresource',
            name='cleanup_buffer_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='propertyresource',
            name='setup_buffer_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='venuebooking',
            name='is_full_property',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ResourceDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requires', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_by', to='api.propertyresource')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='api.propertyresource')),
            ],
        ),
    ]
