# Generated by Django 5.2.14 on 2026-06-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_propertyresource_cleanup_buffer_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='aadhaar_photo',
            field=models.ImageField(blank=True, null=True, upload_to='aadhaar_photos/'),
        ),
    ]
