/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MatrimonyRouteImport } from './routes/matrimony'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CommunityAdminRouteImport } from './routes/community-admin'
import { Route as CommunitiesRouteImport } from './routes/communities'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterIndexRouteImport } from './routes/register.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as CommunityAdminIndexRouteImport } from './routes/community-admin.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as RegisterCommunityRouteImport } from './routes/register.community'
import { Route as DashboardVenuesRouteImport } from './routes/dashboard.venues'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardPlanRouteImport } from './routes/dashboard.plan'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardMessagesRouteImport } from './routes/dashboard.messages'
import { Route as DashboardMatrimonyRouteImport } from './routes/dashboard.matrimony'
import { Route as DashboardJobsRouteImport } from './routes/dashboard.jobs'
import { Route as DashboardHierarchyRouteImport } from './routes/dashboard.hierarchy'
import { Route as DashboardFamilyRouteImport } from './routes/dashboard.family'
import { Route as DashboardEventsRouteImport } from './routes/dashboard.events'
import { Route as DashboardDonationsRouteImport } from './routes/dashboard.donations'
import { Route as DashboardDirectoryRouteImport } from './routes/dashboard.directory'
import { Route as DashboardBusinessRouteImport } from './routes/dashboard.business'
import { Route as CommunityAdminVenuesRouteImport } from './routes/community-admin.venues'
import { Route as CommunityAdminSubsidiariesRouteImport } from './routes/community-admin.subsidiaries'
import { Route as CommunityAdminSettingsRouteImport } from './routes/community-admin.settings'
import { Route as CommunityAdminReportsRouteImport } from './routes/community-admin.reports'
import { Route as CommunityAdminPlanRouteImport } from './routes/community-admin.plan'
import { Route as CommunityAdminNewsRouteImport } from './routes/community-admin.news'
import { Route as CommunityAdminMembersRouteImport } from './routes/community-admin.members'
import { Route as CommunityAdminMatrimonyRouteImport } from './routes/community-admin.matrimony'
import { Route as CommunityAdminJobsRouteImport } from './routes/community-admin.jobs'
import { Route as CommunityAdminHierarchyRouteImport } from './routes/community-admin.hierarchy'
import { Route as CommunityAdminGalleryRouteImport } from './routes/community-admin.gallery'
import { Route as CommunityAdminFamiliesRouteImport } from './routes/community-admin.families'
import { Route as CommunityAdminEventsRouteImport } from './routes/community-admin.events'
import { Route as CommunityAdminDonationsRouteImport } from './routes/community-admin.donations'
import { Route as CommunityAdminCommitteeRouteImport } from './routes/community-admin.committee'
import { Route as CommunityAdminBusinessesRouteImport } from './routes/community-admin.businesses'
import { Route as CommunityAdminAdvertisementsRouteImport } from './routes/community-admin.advertisements'
import { Route as AdminVenuesRouteImport } from './routes/admin.venues'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminMembersRouteImport } from './routes/admin.members'
import { Route as AdminMatrimonyRouteImport } from './routes/admin.matrimony'
import { Route as AdminJobsBusinessesRouteImport } from './routes/admin.jobs-businesses'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminDonationsRouteImport } from './routes/admin.donations'
import { Route as AdminCommunityHierarchyRouteImport } from './routes/admin.community-hierarchy'
import { Route as AdminCommunitiesRouteImport } from './routes/admin.communities'
import { Route as AdminCommitteeRouteImport } from './routes/admin.committee'
import { Route as AdminCmsRouteImport } from './routes/admin.cms'
import { Route as AdminAdvertisementsRouteImport } from './routes/admin.advertisements'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MatrimonyRoute = MatrimonyRouteImport.update({
  id: '/matrimony',
  path: '/matrimony',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityAdminRoute = CommunityAdminRouteImport.update({
  id: '/community-admin',
  path: '/community-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesRoute = CommunitiesRouteImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RegisterRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const CommunityAdminIndexRoute = CommunityAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CommunityAdminRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const RegisterCommunityRoute = RegisterCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => RegisterRoute,
} as any)
const DashboardVenuesRoute = DashboardVenuesRouteImport.update({
  id: '/venues',
  path: '/venues',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlanRoute = DashboardPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMatrimonyRoute = DashboardMatrimonyRouteImport.update({
  id: '/matrimony',
  path: '/matrimony',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJobsRoute = DashboardJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHierarchyRoute = DashboardHierarchyRouteImport.update({
  id: '/hierarchy',
  path: '/hierarchy',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFamilyRoute = DashboardFamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEventsRoute = DashboardEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDonationsRoute = DashboardDonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDirectoryRoute = DashboardDirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBusinessRoute = DashboardBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => DashboardRoute,
} as any)
const CommunityAdminVenuesRoute = CommunityAdminVenuesRouteImport.update({
  id: '/venues',
  path: '/venues',
  getParentRoute: () => CommunityAdminRoute,
} as any)
const CommunityAdminSubsidiariesRoute =
  CommunityAdminSubsidiariesRouteImport.update({
    id: '/subsidiaries',
    path: '/subsidiaries',
    getParentRoute: () => CommunityAdminRoute,
  } as any)
const CommunityAdminSettingsRoute = CommunityAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CommunityAdminRoute,
} as any)
const CommunityAdminReportsRoute = CommunityAdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => CommunityAdminRoute,
} as any)
const CommunityAdminPlanRoute = CommunityAdminPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => CommunityAdminRoute,
} as any)
const CommunityAdminNewsRoute = CommunityAdminNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => CommunityAdminRoute,
} as any)
const CommunityAdminMembersRoute = CommunityAdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => CommunityAdminRoute,
} as any)
const CommunityAdminMatrimonyRoute = CommunityAdminMatrimonyRouteImport.update({
  id: '/matrimony',
  path: '/matrimony',
  getParentRoute: () => CommunityAdminRoute,
} as any)
const CommunityAdminJobsRoute = CommunityAdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => CommunityAdminRoute,
} as any)
const CommunityAdminHierarchyRoute = CommunityAdminHierarchyRouteImport.update({
  id: '/hierarchy',
  path: '/hierarchy',
  getParentRoute: () => CommunityAdminRoute,
} as any)
const CommunityAdminGalleryRoute = CommunityAdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => CommunityAdminRoute,
} as any)
const CommunityAdminFamiliesRoute = CommunityAdminFamiliesRouteImport.update({
  id: '/families',
  path: '/families',
  getParentRoute: () => CommunityAdminRoute,
} as any)
const CommunityAdminEventsRoute = CommunityAdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => CommunityAdminRoute,
} as any)
const CommunityAdminDonationsRoute = CommunityAdminDonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => CommunityAdminRoute,
} as any)
const CommunityAdminCommitteeRoute = CommunityAdminCommitteeRouteImport.update({
  id: '/committee',
  path: '/committee',
  getParentRoute: () => CommunityAdminRoute,
} as any)
const CommunityAdminBusinessesRoute =
  CommunityAdminBusinessesRouteImport.update({
    id: '/businesses',
    path: '/businesses',
    getParentRoute: () => CommunityAdminRoute,
  } as any)
const CommunityAdminAdvertisementsRoute =
  CommunityAdminAdvertisementsRouteImport.update({
    id: '/advertisements',
    path: '/advertisements',
    getParentRoute: () => CommunityAdminRoute,
  } as any)
const AdminVenuesRoute = AdminVenuesRouteImport.update({
  id: '/venues',
  path: '/venues',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMatrimonyRoute = AdminMatrimonyRouteImport.update({
  id: '/matrimony',
  path: '/matrimony',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsBusinessesRoute = AdminJobsBusinessesRouteImport.update({
  id: '/jobs-businesses',
  path: '/jobs-businesses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDonationsRoute = AdminDonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommunityHierarchyRoute = AdminCommunityHierarchyRouteImport.update({
  id: '/community-hierarchy',
  path: '/community-hierarchy',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommunitiesRoute = AdminCommunitiesRouteImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommitteeRoute = AdminCommitteeRouteImport.update({
  id: '/committee',
  path: '/committee',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsRoute = AdminCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdvertisementsRoute = AdminAdvertisementsRouteImport.update({
  id: '/advertisements',
  path: '/advertisements',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/communities': typeof CommunitiesRoute
  '/community-admin': typeof CommunityAdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/directory': typeof DirectoryRoute
  '/events': typeof EventsRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/matrimony': typeof MatrimonyRoute
  '/register': typeof RegisterRouteWithChildren
  '/admin/advertisements': typeof AdminAdvertisementsRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/committee': typeof AdminCommitteeRoute
  '/admin/communities': typeof AdminCommunitiesRoute
  '/admin/community-hierarchy': typeof AdminCommunityHierarchyRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/jobs-businesses': typeof AdminJobsBusinessesRoute
  '/admin/matrimony': typeof AdminMatrimonyRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/venues': typeof AdminVenuesRoute
  '/community-admin/advertisements': typeof CommunityAdminAdvertisementsRoute
  '/community-admin/businesses': typeof CommunityAdminBusinessesRoute
  '/community-admin/committee': typeof CommunityAdminCommitteeRoute
  '/community-admin/donations': typeof CommunityAdminDonationsRoute
  '/community-admin/events': typeof CommunityAdminEventsRoute
  '/community-admin/families': typeof CommunityAdminFamiliesRoute
  '/community-admin/gallery': typeof CommunityAdminGalleryRoute
  '/community-admin/hierarchy': typeof CommunityAdminHierarchyRoute
  '/community-admin/jobs': typeof CommunityAdminJobsRoute
  '/community-admin/matrimony': typeof CommunityAdminMatrimonyRoute
  '/community-admin/members': typeof CommunityAdminMembersRoute
  '/community-admin/news': typeof CommunityAdminNewsRoute
  '/community-admin/plan': typeof CommunityAdminPlanRoute
  '/community-admin/reports': typeof CommunityAdminReportsRoute
  '/community-admin/settings': typeof CommunityAdminSettingsRoute
  '/community-admin/subsidiaries': typeof CommunityAdminSubsidiariesRoute
  '/community-admin/venues': typeof CommunityAdminVenuesRoute
  '/dashboard/business': typeof DashboardBusinessRoute
  '/dashboard/directory': typeof DashboardDirectoryRoute
  '/dashboard/donations': typeof DashboardDonationsRoute
  '/dashboard/events': typeof DashboardEventsRoute
  '/dashboard/family': typeof DashboardFamilyRoute
  '/dashboard/hierarchy': typeof DashboardHierarchyRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/matrimony': typeof DashboardMatrimonyRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/plan': typeof DashboardPlanRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/venues': typeof DashboardVenuesRoute
  '/register/community': typeof RegisterCommunityRoute
  '/admin/': typeof AdminIndexRoute
  '/community-admin/': typeof CommunityAdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/register/': typeof RegisterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/communities': typeof CommunitiesRoute
  '/directory': typeof DirectoryRoute
  '/events': typeof EventsRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/matrimony': typeof MatrimonyRoute
  '/admin/advertisements': typeof AdminAdvertisementsRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/committee': typeof AdminCommitteeRoute
  '/admin/communities': typeof AdminCommunitiesRoute
  '/admin/community-hierarchy': typeof AdminCommunityHierarchyRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/jobs-businesses': typeof AdminJobsBusinessesRoute
  '/admin/matrimony': typeof AdminMatrimonyRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/venues': typeof AdminVenuesRoute
  '/community-admin/advertisements': typeof CommunityAdminAdvertisementsRoute
  '/community-admin/businesses': typeof CommunityAdminBusinessesRoute
  '/community-admin/committee': typeof CommunityAdminCommitteeRoute
  '/community-admin/donations': typeof CommunityAdminDonationsRoute
  '/community-admin/events': typeof CommunityAdminEventsRoute
  '/community-admin/families': typeof CommunityAdminFamiliesRoute
  '/community-admin/gallery': typeof CommunityAdminGalleryRoute
  '/community-admin/hierarchy': typeof CommunityAdminHierarchyRoute
  '/community-admin/jobs': typeof CommunityAdminJobsRoute
  '/community-admin/matrimony': typeof CommunityAdminMatrimonyRoute
  '/community-admin/members': typeof CommunityAdminMembersRoute
  '/community-admin/news': typeof CommunityAdminNewsRoute
  '/community-admin/plan': typeof CommunityAdminPlanRoute
  '/community-admin/reports': typeof CommunityAdminReportsRoute
  '/community-admin/settings': typeof CommunityAdminSettingsRoute
  '/community-admin/subsidiaries': typeof CommunityAdminSubsidiariesRoute
  '/community-admin/venues': typeof CommunityAdminVenuesRoute
  '/dashboard/business': typeof DashboardBusinessRoute
  '/dashboard/directory': typeof DashboardDirectoryRoute
  '/dashboard/donations': typeof DashboardDonationsRoute
  '/dashboard/events': typeof DashboardEventsRoute
  '/dashboard/family': typeof DashboardFamilyRoute
  '/dashboard/hierarchy': typeof DashboardHierarchyRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/matrimony': typeof DashboardMatrimonyRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/plan': typeof DashboardPlanRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/venues': typeof DashboardVenuesRoute
  '/register/community': typeof RegisterCommunityRoute
  '/admin': typeof AdminIndexRoute
  '/community-admin': typeof CommunityAdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/register': typeof RegisterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/communities': typeof CommunitiesRoute
  '/community-admin': typeof CommunityAdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/directory': typeof DirectoryRoute
  '/events': typeof EventsRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/matrimony': typeof MatrimonyRoute
  '/register': typeof RegisterRouteWithChildren
  '/admin/advertisements': typeof AdminAdvertisementsRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/committee': typeof AdminCommitteeRoute
  '/admin/communities': typeof AdminCommunitiesRoute
  '/admin/community-hierarchy': typeof AdminCommunityHierarchyRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/jobs-businesses': typeof AdminJobsBusinessesRoute
  '/admin/matrimony': typeof AdminMatrimonyRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/venues': typeof AdminVenuesRoute
  '/community-admin/advertisements': typeof CommunityAdminAdvertisementsRoute
  '/community-admin/businesses': typeof CommunityAdminBusinessesRoute
  '/community-admin/committee': typeof CommunityAdminCommitteeRoute
  '/community-admin/donations': typeof CommunityAdminDonationsRoute
  '/community-admin/events': typeof CommunityAdminEventsRoute
  '/community-admin/families': typeof CommunityAdminFamiliesRoute
  '/community-admin/gallery': typeof CommunityAdminGalleryRoute
  '/community-admin/hierarchy': typeof CommunityAdminHierarchyRoute
  '/community-admin/jobs': typeof CommunityAdminJobsRoute
  '/community-admin/matrimony': typeof CommunityAdminMatrimonyRoute
  '/community-admin/members': typeof CommunityAdminMembersRoute
  '/community-admin/news': typeof CommunityAdminNewsRoute
  '/community-admin/plan': typeof CommunityAdminPlanRoute
  '/community-admin/reports': typeof CommunityAdminReportsRoute
  '/community-admin/settings': typeof CommunityAdminSettingsRoute
  '/community-admin/subsidiaries': typeof CommunityAdminSubsidiariesRoute
  '/community-admin/venues': typeof CommunityAdminVenuesRoute
  '/dashboard/business': typeof DashboardBusinessRoute
  '/dashboard/directory': typeof DashboardDirectoryRoute
  '/dashboard/donations': typeof DashboardDonationsRoute
  '/dashboard/events': typeof DashboardEventsRoute
  '/dashboard/family': typeof DashboardFamilyRoute
  '/dashboard/hierarchy': typeof DashboardHierarchyRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/matrimony': typeof DashboardMatrimonyRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/plan': typeof DashboardPlanRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/venues': typeof DashboardVenuesRoute
  '/register/community': typeof RegisterCommunityRoute
  '/admin/': typeof AdminIndexRoute
  '/community-admin/': typeof CommunityAdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/register/': typeof RegisterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/communities'
    | '/community-admin'
    | '/dashboard'
    | '/directory'
    | '/events'
    | '/jobs'
    | '/login'
    | '/matrimony'
    | '/register'
    | '/admin/advertisements'
    | '/admin/cms'
    | '/admin/committee'
    | '/admin/communities'
    | '/admin/community-hierarchy'
    | '/admin/donations'
    | '/admin/events'
    | '/admin/jobs-businesses'
    | '/admin/matrimony'
    | '/admin/members'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/venues'
    | '/community-admin/advertisements'
    | '/community-admin/businesses'
    | '/community-admin/committee'
    | '/community-admin/donations'
    | '/community-admin/events'
    | '/community-admin/families'
    | '/community-admin/gallery'
    | '/community-admin/hierarchy'
    | '/community-admin/jobs'
    | '/community-admin/matrimony'
    | '/community-admin/members'
    | '/community-admin/news'
    | '/community-admin/plan'
    | '/community-admin/reports'
    | '/community-admin/settings'
    | '/community-admin/subsidiaries'
    | '/community-admin/venues'
    | '/dashboard/business'
    | '/dashboard/directory'
    | '/dashboard/donations'
    | '/dashboard/events'
    | '/dashboard/family'
    | '/dashboard/hierarchy'
    | '/dashboard/jobs'
    | '/dashboard/matrimony'
    | '/dashboard/messages'
    | '/dashboard/notifications'
    | '/dashboard/plan'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/venues'
    | '/register/community'
    | '/admin/'
    | '/community-admin/'
    | '/dashboard/'
    | '/register/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/communities'
    | '/directory'
    | '/events'
    | '/jobs'
    | '/login'
    | '/matrimony'
    | '/admin/advertisements'
    | '/admin/cms'
    | '/admin/committee'
    | '/admin/communities'
    | '/admin/community-hierarchy'
    | '/admin/donations'
    | '/admin/events'
    | '/admin/jobs-businesses'
    | '/admin/matrimony'
    | '/admin/members'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/venues'
    | '/community-admin/advertisements'
    | '/community-admin/businesses'
    | '/community-admin/committee'
    | '/community-admin/donations'
    | '/community-admin/events'
    | '/community-admin/families'
    | '/community-admin/gallery'
    | '/community-admin/hierarchy'
    | '/community-admin/jobs'
    | '/community-admin/matrimony'
    | '/community-admin/members'
    | '/community-admin/news'
    | '/community-admin/plan'
    | '/community-admin/reports'
    | '/community-admin/settings'
    | '/community-admin/subsidiaries'
    | '/community-admin/venues'
    | '/dashboard/business'
    | '/dashboard/directory'
    | '/dashboard/donations'
    | '/dashboard/events'
    | '/dashboard/family'
    | '/dashboard/hierarchy'
    | '/dashboard/jobs'
    | '/dashboard/matrimony'
    | '/dashboard/messages'
    | '/dashboard/notifications'
    | '/dashboard/plan'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/venues'
    | '/register/community'
    | '/admin'
    | '/community-admin'
    | '/dashboard'
    | '/register'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/communities'
    | '/community-admin'
    | '/dashboard'
    | '/directory'
    | '/events'
    | '/jobs'
    | '/login'
    | '/matrimony'
    | '/register'
    | '/admin/advertisements'
    | '/admin/cms'
    | '/admin/committee'
    | '/admin/communities'
    | '/admin/community-hierarchy'
    | '/admin/donations'
    | '/admin/events'
    | '/admin/jobs-businesses'
    | '/admin/matrimony'
    | '/admin/members'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/venues'
    | '/community-admin/advertisements'
    | '/community-admin/businesses'
    | '/community-admin/committee'
    | '/community-admin/donations'
    | '/community-admin/events'
    | '/community-admin/families'
    | '/community-admin/gallery'
    | '/community-admin/hierarchy'
    | '/community-admin/jobs'
    | '/community-admin/matrimony'
    | '/community-admin/members'
    | '/community-admin/news'
    | '/community-admin/plan'
    | '/community-admin/reports'
    | '/community-admin/settings'
    | '/community-admin/subsidiaries'
    | '/community-admin/venues'
    | '/dashboard/business'
    | '/dashboard/directory'
    | '/dashboard/donations'
    | '/dashboard/events'
    | '/dashboard/family'
    | '/dashboard/hierarchy'
    | '/dashboard/jobs'
    | '/dashboard/matrimony'
    | '/dashboard/messages'
    | '/dashboard/notifications'
    | '/dashboard/plan'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/venues'
    | '/register/community'
    | '/admin/'
    | '/community-admin/'
    | '/dashboard/'
    | '/register/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CommunitiesRoute: typeof CommunitiesRoute
  CommunityAdminRoute: typeof CommunityAdminRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  DirectoryRoute: typeof DirectoryRoute
  EventsRoute: typeof EventsRoute
  JobsRoute: typeof JobsRoute
  LoginRoute: typeof LoginRoute
  MatrimonyRoute: typeof MatrimonyRoute
  RegisterRoute: typeof RegisterRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matrimony': {
      id: '/matrimony'
      path: '/matrimony'
      fullPath: '/matrimony'
      preLoaderRoute: typeof MatrimonyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-admin': {
      id: '/community-admin'
      path: '/community-admin'
      fullPath: '/community-admin'
      preLoaderRoute: typeof CommunityAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities': {
      id: '/communities'
      path: '/communities'
      fullPath: '/communities'
      preLoaderRoute: typeof CommunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/community-admin/': {
      id: '/community-admin/'
      path: '/'
      fullPath: '/community-admin/'
      preLoaderRoute: typeof CommunityAdminIndexRouteImport
      parentRoute: typeof CommunityAdminRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/register/community': {
      id: '/register/community'
      path: '/community'
      fullPath: '/register/community'
      preLoaderRoute: typeof RegisterCommunityRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/dashboard/venues': {
      id: '/dashboard/venues'
      path: '/venues'
      fullPath: '/dashboard/venues'
      preLoaderRoute: typeof DashboardVenuesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/plan': {
      id: '/dashboard/plan'
      path: '/plan'
      fullPath: '/dashboard/plan'
      preLoaderRoute: typeof DashboardPlanRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/matrimony': {
      id: '/dashboard/matrimony'
      path: '/matrimony'
      fullPath: '/dashboard/matrimony'
      preLoaderRoute: typeof DashboardMatrimonyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/jobs': {
      id: '/dashboard/jobs'
      path: '/jobs'
      fullPath: '/dashboard/jobs'
      preLoaderRoute: typeof DashboardJobsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/hierarchy': {
      id: '/dashboard/hierarchy'
      path: '/hierarchy'
      fullPath: '/dashboard/hierarchy'
      preLoaderRoute: typeof DashboardHierarchyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/family': {
      id: '/dashboard/family'
      path: '/family'
      fullPath: '/dashboard/family'
      preLoaderRoute: typeof DashboardFamilyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/events': {
      id: '/dashboard/events'
      path: '/events'
      fullPath: '/dashboard/events'
      preLoaderRoute: typeof DashboardEventsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/donations': {
      id: '/dashboard/donations'
      path: '/donations'
      fullPath: '/dashboard/donations'
      preLoaderRoute: typeof DashboardDonationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/directory': {
      id: '/dashboard/directory'
      path: '/directory'
      fullPath: '/dashboard/directory'
      preLoaderRoute: typeof DashboardDirectoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/business': {
      id: '/dashboard/business'
      path: '/business'
      fullPath: '/dashboard/business'
      preLoaderRoute: typeof DashboardBusinessRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/community-admin/venues': {
      id: '/community-admin/venues'
      path: '/venues'
      fullPath: '/community-admin/venues'
      preLoaderRoute: typeof CommunityAdminVenuesRouteImport
      parentRoute: typeof CommunityAdminRoute
    }
    '/community-admin/subsidiaries': {
      id: '/community-admin/subsidiaries'
      path: '/subsidiaries'
      fullPath: '/community-admin/subsidiaries'
      preLoaderRoute: typeof CommunityAdminSubsidiariesRouteImport
      parentRoute: typeof CommunityAdminRoute
    }
    '/community-admin/settings': {
      id: '/community-admin/settings'
      path: '/settings'
      fullPath: '/community-admin/settings'
      preLoaderRoute: typeof CommunityAdminSettingsRouteImport
      parentRoute: typeof CommunityAdminRoute
    }
    '/community-admin/reports': {
      id: '/community-admin/reports'
      path: '/reports'
      fullPath: '/community-admin/reports'
      preLoaderRoute: typeof CommunityAdminReportsRouteImport
      parentRoute: typeof CommunityAdminRoute
    }
    '/community-admin/plan': {
      id: '/community-admin/plan'
      path: '/plan'
      fullPath: '/community-admin/plan'
      preLoaderRoute: typeof CommunityAdminPlanRouteImport
      parentRoute: typeof CommunityAdminRoute
    }
    '/community-admin/news': {
      id: '/community-admin/news'
      path: '/news'
      fullPath: '/community-admin/news'
      preLoaderRoute: typeof CommunityAdminNewsRouteImport
      parentRoute: typeof CommunityAdminRoute
    }
    '/community-admin/members': {
      id: '/community-admin/members'
      path: '/members'
      fullPath: '/community-admin/members'
      preLoaderRoute: typeof CommunityAdminMembersRouteImport
      parentRoute: typeof CommunityAdminRoute
    }
    '/community-admin/matrimony': {
      id: '/community-admin/matrimony'
      path: '/matrimony'
      fullPath: '/community-admin/matrimony'
      preLoaderRoute: typeof CommunityAdminMatrimonyRouteImport
      parentRoute: typeof CommunityAdminRoute
    }
    '/community-admin/jobs': {
      id: '/community-admin/jobs'
      path: '/jobs'
      fullPath: '/community-admin/jobs'
      preLoaderRoute: typeof CommunityAdminJobsRouteImport
      parentRoute: typeof CommunityAdminRoute
    }
    '/community-admin/hierarchy': {
      id: '/community-admin/hierarchy'
      path: '/hierarchy'
      fullPath: '/community-admin/hierarchy'
      preLoaderRoute: typeof CommunityAdminHierarchyRouteImport
      parentRoute: typeof CommunityAdminRoute
    }
    '/community-admin/gallery': {
      id: '/community-admin/gallery'
      path: '/gallery'
      fullPath: '/community-admin/gallery'
      preLoaderRoute: typeof CommunityAdminGalleryRouteImport
      parentRoute: typeof CommunityAdminRoute
    }
    '/community-admin/families': {
      id: '/community-admin/families'
      path: '/families'
      fullPath: '/community-admin/families'
      preLoaderRoute: typeof CommunityAdminFamiliesRouteImport
      parentRoute: typeof CommunityAdminRoute
    }
    '/community-admin/events': {
      id: '/community-admin/events'
      path: '/events'
      fullPath: '/community-admin/events'
      preLoaderRoute: typeof CommunityAdminEventsRouteImport
      parentRoute: typeof CommunityAdminRoute
    }
    '/community-admin/donations': {
      id: '/community-admin/donations'
      path: '/donations'
      fullPath: '/community-admin/donations'
      preLoaderRoute: typeof CommunityAdminDonationsRouteImport
      parentRoute: typeof CommunityAdminRoute
    }
    '/community-admin/committee': {
      id: '/community-admin/committee'
      path: '/committee'
      fullPath: '/community-admin/committee'
      preLoaderRoute: typeof CommunityAdminCommitteeRouteImport
      parentRoute: typeof CommunityAdminRoute
    }
    '/community-admin/businesses': {
      id: '/community-admin/businesses'
      path: '/businesses'
      fullPath: '/community-admin/businesses'
      preLoaderRoute: typeof CommunityAdminBusinessesRouteImport
      parentRoute: typeof CommunityAdminRoute
    }
    '/community-admin/advertisements': {
      id: '/community-admin/advertisements'
      path: '/advertisements'
      fullPath: '/community-admin/advertisements'
      preLoaderRoute: typeof CommunityAdminAdvertisementsRouteImport
      parentRoute: typeof CommunityAdminRoute
    }
    '/admin/venues': {
      id: '/admin/venues'
      path: '/venues'
      fullPath: '/admin/venues'
      preLoaderRoute: typeof AdminVenuesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/matrimony': {
      id: '/admin/matrimony'
      path: '/matrimony'
      fullPath: '/admin/matrimony'
      preLoaderRoute: typeof AdminMatrimonyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs-businesses': {
      id: '/admin/jobs-businesses'
      path: '/jobs-businesses'
      fullPath: '/admin/jobs-businesses'
      preLoaderRoute: typeof AdminJobsBusinessesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/donations': {
      id: '/admin/donations'
      path: '/donations'
      fullPath: '/admin/donations'
      preLoaderRoute: typeof AdminDonationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/community-hierarchy': {
      id: '/admin/community-hierarchy'
      path: '/community-hierarchy'
      fullPath: '/admin/community-hierarchy'
      preLoaderRoute: typeof AdminCommunityHierarchyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/communities': {
      id: '/admin/communities'
      path: '/communities'
      fullPath: '/admin/communities'
      preLoaderRoute: typeof AdminCommunitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/committee': {
      id: '/admin/committee'
      path: '/committee'
      fullPath: '/admin/committee'
      preLoaderRoute: typeof AdminCommitteeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms': {
      id: '/admin/cms'
      path: '/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AdminCmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/advertisements': {
      id: '/admin/advertisements'
      path: '/advertisements'
      fullPath: '/admin/advertisements'
      preLoaderRoute: typeof AdminAdvertisementsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdvertisementsRoute: typeof AdminAdvertisementsRoute
  AdminCmsRoute: typeof AdminCmsRoute
  AdminCommitteeRoute: typeof AdminCommitteeRoute
  AdminCommunitiesRoute: typeof AdminCommunitiesRoute
  AdminCommunityHierarchyRoute: typeof AdminCommunityHierarchyRoute
  AdminDonationsRoute: typeof AdminDonationsRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminJobsBusinessesRoute: typeof AdminJobsBusinessesRoute
  AdminMatrimonyRoute: typeof AdminMatrimonyRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminVenuesRoute: typeof AdminVenuesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdvertisementsRoute: AdminAdvertisementsRoute,
  AdminCmsRoute: AdminCmsRoute,
  AdminCommitteeRoute: AdminCommitteeRoute,
  AdminCommunitiesRoute: AdminCommunitiesRoute,
  AdminCommunityHierarchyRoute: AdminCommunityHierarchyRoute,
  AdminDonationsRoute: AdminDonationsRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminJobsBusinessesRoute: AdminJobsBusinessesRoute,
  AdminMatrimonyRoute: AdminMatrimonyRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminVenuesRoute: AdminVenuesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CommunityAdminRouteChildren {
  CommunityAdminAdvertisementsRoute: typeof CommunityAdminAdvertisementsRoute
  CommunityAdminBusinessesRoute: typeof CommunityAdminBusinessesRoute
  CommunityAdminCommitteeRoute: typeof CommunityAdminCommitteeRoute
  CommunityAdminDonationsRoute: typeof CommunityAdminDonationsRoute
  CommunityAdminEventsRoute: typeof CommunityAdminEventsRoute
  CommunityAdminFamiliesRoute: typeof CommunityAdminFamiliesRoute
  CommunityAdminGalleryRoute: typeof CommunityAdminGalleryRoute
  CommunityAdminHierarchyRoute: typeof CommunityAdminHierarchyRoute
  CommunityAdminJobsRoute: typeof CommunityAdminJobsRoute
  CommunityAdminMatrimonyRoute: typeof CommunityAdminMatrimonyRoute
  CommunityAdminMembersRoute: typeof CommunityAdminMembersRoute
  CommunityAdminNewsRoute: typeof CommunityAdminNewsRoute
  CommunityAdminPlanRoute: typeof CommunityAdminPlanRoute
  CommunityAdminReportsRoute: typeof CommunityAdminReportsRoute
  CommunityAdminSettingsRoute: typeof CommunityAdminSettingsRoute
  CommunityAdminSubsidiariesRoute: typeof CommunityAdminSubsidiariesRoute
  CommunityAdminVenuesRoute: typeof CommunityAdminVenuesRoute
  CommunityAdminIndexRoute: typeof CommunityAdminIndexRoute
}

const CommunityAdminRouteChildren: CommunityAdminRouteChildren = {
  CommunityAdminAdvertisementsRoute: CommunityAdminAdvertisementsRoute,
  CommunityAdminBusinessesRoute: CommunityAdminBusinessesRoute,
  CommunityAdminCommitteeRoute: CommunityAdminCommitteeRoute,
  CommunityAdminDonationsRoute: CommunityAdminDonationsRoute,
  CommunityAdminEventsRoute: CommunityAdminEventsRoute,
  CommunityAdminFamiliesRoute: CommunityAdminFamiliesRoute,
  CommunityAdminGalleryRoute: CommunityAdminGalleryRoute,
  CommunityAdminHierarchyRoute: CommunityAdminHierarchyRoute,
  CommunityAdminJobsRoute: CommunityAdminJobsRoute,
  CommunityAdminMatrimonyRoute: CommunityAdminMatrimonyRoute,
  CommunityAdminMembersRoute: CommunityAdminMembersRoute,
  CommunityAdminNewsRoute: CommunityAdminNewsRoute,
  CommunityAdminPlanRoute: CommunityAdminPlanRoute,
  CommunityAdminReportsRoute: CommunityAdminReportsRoute,
  CommunityAdminSettingsRoute: CommunityAdminSettingsRoute,
  CommunityAdminSubsidiariesRoute: CommunityAdminSubsidiariesRoute,
  CommunityAdminVenuesRoute: CommunityAdminVenuesRoute,
  CommunityAdminIndexRoute: CommunityAdminIndexRoute,
}

const CommunityAdminRouteWithChildren = CommunityAdminRoute._addFileChildren(
  CommunityAdminRouteChildren,
)

interface DashboardRouteChildren {
  DashboardBusinessRoute: typeof DashboardBusinessRoute
  DashboardDirectoryRoute: typeof DashboardDirectoryRoute
  DashboardDonationsRoute: typeof DashboardDonationsRoute
  DashboardEventsRoute: typeof DashboardEventsRoute
  DashboardFamilyRoute: typeof DashboardFamilyRoute
  DashboardHierarchyRoute: typeof DashboardHierarchyRoute
  DashboardJobsRoute: typeof DashboardJobsRoute
  DashboardMatrimonyRoute: typeof DashboardMatrimonyRoute
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardPlanRoute: typeof DashboardPlanRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardVenuesRoute: typeof DashboardVenuesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBusinessRoute: DashboardBusinessRoute,
  DashboardDirectoryRoute: DashboardDirectoryRoute,
  DashboardDonationsRoute: DashboardDonationsRoute,
  DashboardEventsRoute: DashboardEventsRoute,
  DashboardFamilyRoute: DashboardFamilyRoute,
  DashboardHierarchyRoute: DashboardHierarchyRoute,
  DashboardJobsRoute: DashboardJobsRoute,
  DashboardMatrimonyRoute: DashboardMatrimonyRoute,
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardPlanRoute: DashboardPlanRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardVenuesRoute: DashboardVenuesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface RegisterRouteChildren {
  RegisterCommunityRoute: typeof RegisterCommunityRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
}

const RegisterRouteChildren: RegisterRouteChildren = {
  RegisterCommunityRoute: RegisterCommunityRoute,
  RegisterIndexRoute: RegisterIndexRoute,
}

const RegisterRouteWithChildren = RegisterRoute._addFileChildren(
  RegisterRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CommunitiesRoute: CommunitiesRoute,
  CommunityAdminRoute: CommunityAdminRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  DirectoryRoute: DirectoryRoute,
  EventsRoute: EventsRoute,
  JobsRoute: JobsRoute,
  LoginRoute: LoginRoute,
  MatrimonyRoute: MatrimonyRoute,
  RegisterRoute: RegisterRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
